name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.22'
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v1.62.2

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.3.0
        with:
          go-version: '1.22'
      - run: go test -v ./...
